kind: Service
apiVersion: v1
metadata:
  name: emporium-service
  namespace: binaryit
spec:
  type: NodePort
  ports:
    - name: http
      port: 30080
      targetPort: 80
      protocol: TCP
    # - name: httpsk
    #   port: 443
    #   targetPort: 3002 
    #   protocol: TCP
  selector:
    app: emporium